package budget;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 * @author Fernando Ponce Soís
 */

public class Window extends javax.swing.JFrame {
    //<editor-fold defaultstate="collapsed" desc="Variabe and Constants Initialization/Declaration">
    float balance;
    String money;
    
    final FileRead file = new FileRead();
    final Color POSITIVE = new Color(5, 0, 255);
    final Color NEGATIVE = new Color(190, 6, 17);
    
    private static final ImageIcon icon = new ImageIcon(Window.class.getResource("/icon/Money.png"));
        //Iconos diseñados por https://www.freepik.com
    //</editor-fold>
  
    
    /**
     * Creates new form Window
     */
 
    
    public Window() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseText = new javax.swing.JPanel();
        btnMenu = new javax.swing.JPanel();
        rect = new javax.swing.JPanel();
        rect2 = new javax.swing.JPanel();
        rect3 = new javax.swing.JPanel();
        txtTransference = new javax.swing.JTextField();
        btnPayed = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JLabel();
        btnSpent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBalance = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saving Budget");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baseText.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(baseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 107, 250, 4));

        btnMenu.setBackground(new java.awt.Color(57, 86, 240));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        btnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rect.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu.add(rect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 7));

        rect2.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu.add(rect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 7));

        rect3.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu.add(rect3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 7));

        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 11, 30, 27));

        txtTransference.setBackground(new java.awt.Color(57, 86, 240));
        txtTransference.setFont(new java.awt.Font("Roboto", 0, 64)); // NOI18N
        txtTransference.setForeground(new java.awt.Color(255, 255, 255));
        txtTransference.setBorder(null);
        txtTransference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransferenceActionPerformed(evt);
            }
        });
        getContentPane().add(txtTransference, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 60));

        btnPayed.setBackground(new java.awt.Color(109, 255, 229));
        btnPayed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPayedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPayedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPayedMouseExited(evt);
            }
        });
        btnPayed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 47, 243));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagado");
        btnPayed.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        getContentPane().add(btnPayed, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 100, 30));

        txtBalance.setFont(new java.awt.Font("Roboto", 1, 96)); // NOI18N
        getContentPane().add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 400, 100));

        btnSpent.setBackground(new java.awt.Color(0, 39, 249));
        btnSpent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSpentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSpentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSpentMouseExited(evt);
            }
        });
        btnSpent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gastado");
        btnSpent.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        getContentPane().add(btnSpent, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 100, 30));

        btnBalance.setBackground(new java.awt.Color(255, 255, 255));
        btnBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBalanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBalanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBalanceMouseExited(evt);
            }
        });
        btnBalance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 47, 243));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ver Saldo");
        btnBalance.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        getContentPane().add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 100, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Saldo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 225, 94, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Background.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 400));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTransferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransferenceActionPerformed
    }//GEN-LAST:event_txtTransferenceActionPerformed
    
    private void btnPayedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayedMouseEntered
        btnPayed.setBackground(new Color(0, 230, 230));
    }//GEN-LAST:event_btnPayedMouseEntered

    private void btnPayedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayedMouseExited
        btnPayed.setBackground(new Color(109, 255, 229));
    }//GEN-LAST:event_btnPayedMouseExited

    private void btnPayedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayedMouseClicked
        if(txtTransference.getText() == null){
            money = "0";
        }else{
            money = txtTransference.getText();
        }
        balance = file.pay(money);
        if (balance < 0) {
            txtBalance.setForeground(NEGATIVE);
        }else if(balance > 0){
            txtBalance.setForeground(POSITIVE);
        }else{
            txtBalance.setForeground(NEGATIVE);
        }
        txtBalance.setText("$" + balance);
    }//GEN-LAST:event_btnPayedMouseClicked

    private void btnSpentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSpentMouseEntered
        btnSpent.setBackground(new Color(0, 39, 200));
    }//GEN-LAST:event_btnSpentMouseEntered

    private void btnSpentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSpentMouseExited
        btnSpent.setBackground(new Color(0,39,249));
    }//GEN-LAST:event_btnSpentMouseExited

    private void btnSpentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSpentMouseClicked
        if(txtTransference.getText() == null){
            money = "0";
        }else{
            money = txtTransference.getText();
        }
        balance = file.spent(money);
        if (balance < 0) {
            txtBalance.setForeground(NEGATIVE);
        }else if(balance > 0){
            txtBalance.setForeground(POSITIVE);
        }else{
            txtBalance.setForeground(NEGATIVE);
        }
        txtBalance.setText("$" + balance);
    }//GEN-LAST:event_btnSpentMouseClicked

    private void btnBalanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalanceMouseEntered
        btnBalance.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_btnBalanceMouseEntered

    private void btnBalanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalanceMouseExited
        btnBalance.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnBalanceMouseExited

    private void btnBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalanceMouseClicked
        balance = file.getFinalBalance();
        if (balance < 0) {
            txtBalance.setForeground(NEGATIVE);
        }else if(balance > 0){
            txtBalance.setForeground(POSITIVE);
        }else{
            txtBalance.setForeground(NEGATIVE);
        }
        txtBalance.setText("$"+balance);
    }//GEN-LAST:event_btnBalanceMouseClicked

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        rect.setBackground(new Color(230, 230, 230));
        rect2.setBackground(new Color(230, 230, 230));
        rect3.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        rect.setBackground(Color.WHITE);
        rect2.setBackground(Color.WHITE);
        rect3.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
    }//GEN-LAST:event_btnMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baseText;
    private javax.swing.JPanel btnBalance;
    private javax.swing.JPanel btnMenu;
    private javax.swing.JPanel btnPayed;
    private javax.swing.JPanel btnSpent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel rect;
    private javax.swing.JPanel rect2;
    private javax.swing.JPanel rect3;
    private javax.swing.JLabel txtBalance;
    private javax.swing.JTextField txtTransference;
    // End of variables declaration//GEN-END:variables
}
