package budget;

import java.awt.Color;
import javax.swing.ImageIcon;

public class Window extends javax.swing.JFrame {
    FileRead file = new FileRead();
    float balance;
    String money;
    
    private static final ImageIcon icon = new ImageIcon(Window.class.getResource("/icon/Money.png"));
    //Iconos diseñados por https://www.freepik.com
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        setTitle("Saving Budget");
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTransference = new javax.swing.JTextField();
        btnPayed = new javax.swing.JButton();
        btnSpent = new javax.swing.JButton();
        txtBalance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBalance = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 243, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTransference.setBackground(new java.awt.Color(255, 222, 125));
        txtTransference.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        txtTransference.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtTransference, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 322, 72));

        btnPayed.setBackground(new java.awt.Color(0, 184, 169));
        btnPayed.setForeground(new java.awt.Color(255, 255, 255));
        btnPayed.setText("Pagado");
        btnPayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayedActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayed, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 80, 40));

        btnSpent.setBackground(new java.awt.Color(246, 65, 108));
        btnSpent.setForeground(new java.awt.Color(255, 255, 255));
        btnSpent.setText("Gastado");
        btnSpent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpentActionPerformed(evt);
            }
        });
        jPanel1.add(btnSpent, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, 40));

        txtBalance.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jPanel1.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 430, 95));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Ingreso/gasto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 30));

        btnBalance.setBackground(new java.awt.Color(255, 222, 125));
        btnBalance.setForeground(new java.awt.Color(51, 51, 51));
        btnBalance.setText("Saldo");
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 80, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Saldo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, 94, 30));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayedActionPerformed
        if(txtTransference.getText() == null){
            money = "0";
        }else{
            money = txtTransference.getText();
        }
        balance = file.pay(money);
        if (balance < 0) {
            txtBalance.setForeground(Color.RED);
        }else if(balance > 0){
            txtBalance.setForeground(Color.GREEN);
        }else{
            txtBalance.setForeground(Color.WHITE);
        }
        txtBalance.setText("$" + balance);
    }//GEN-LAST:event_btnPayedActionPerformed

    private void btnSpentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpentActionPerformed
        if(txtTransference.getText() == null){
            money = "0";
        }else{
            money = txtTransference.getText();
        }
        balance = file.spent(money);
        if (balance < 0) {
            txtBalance.setForeground(Color.RED);
        }else if(balance > 0){
            txtBalance.setForeground(Color.GREEN);
        }else{
            txtBalance.setForeground(Color.WHITE);
        }
        txtBalance.setText("$" + balance);
    }//GEN-LAST:event_btnSpentActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        balance = file.getFinalBalance();
        if (balance < 0) {
            txtBalance.setForeground(Color.RED);
        }else if(balance > 0){
            txtBalance.setForeground(Color.GREEN);
        }else{
            txtBalance.setForeground(Color.WHITE);
        }
        txtBalance.setText("$"+balance);
    }//GEN-LAST:event_btnBalanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnPayed;
    private javax.swing.JButton btnSpent;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtBalance;
    private javax.swing.JTextField txtTransference;
    // End of variables declaration//GEN-END:variables
}
